# Generated by Django 3.1.7 on 2021-05-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
    ]
